import mickeyMousePortrait from "../assets/counsellor-mickey-mouse.svg";
import hattoriPortrait from "../assets/counsellor-hattori.svg";
import shinchanPortrait from "../assets/counsellor-shinchan.svg";
import doraemonPortrait from "../assets/counsellor-doraemon.svg";

export const COUNSELLORS = [
  {
    id: "mickey-mouse",
    name: "Mickey Mouse",
    civilianName: "Cheerful support guide",
    image: mickeyMousePortrait,
    imageAlt: "Stylized portrait of Mickey Mouse as a counsellor",
    tagline: "Bright, steady support for stressful or busy days.",
    focus: ["Daily stress", "Motivation", "Feeling overwhelmed"],
    style: "Friendly check-ins, simple reframes, and encouraging next steps.",
    availability: "Today • Evening openings",
    formats: ["Video", "Voice", "Chat"],
    fee: "Demo profile",
    accent: "from-rose-500 to-orange-500",
    badgeTone: "bg-rose-50 text-rose-700 ring-rose-200/70",
    bio: "Mickey brings upbeat energy, warmth, and a reassuring tone that helps heavy days feel a little more manageable.",
    slots: [
      "Today • 6:00 PM",
      "Tomorrow • 10:30 AM",
      "Tomorrow • 8:15 PM",
    ],
  },
  {
    id: "hattori",
    name: "Hattori",
    civilianName: "Ninja-style calm guide",
    image: hattoriPortrait,
    imageAlt: "Stylized portrait of a Hattori-style counsellor",
    tagline: "Calm support for focus, confidence, and emotional balance.",
    focus: ["Focus", "Confidence", "School pressure"],
    style: "Gentle listening, calm guidance, and practical problem solving.",
    availability: "Tomorrow • Afternoon openings",
    formats: ["Video", "Voice"],
    fee: "Demo profile",
    accent: "from-amber-500 to-pink-500",
    badgeTone: "bg-amber-50 text-amber-700 ring-amber-200/70",
    bio: "Hattori's sessions feel calm and focused, especially when you want help settling nerves, building confidence, or getting back on track.",
    slots: [
      "Tomorrow • 1:00 PM",
      "Tomorrow • 4:30 PM",
      "Friday • 11:00 AM",
    ],
  },
  {
    id: "shinchan",
    name: "Shinchan",
    civilianName: "Playful mood-lifter",
    image: shinchanPortrait,
    imageAlt: "Stylized portrait of Shinchan as a counsellor",
    tagline: "Light, playful support for burnout, low energy, and overthinking.",
    focus: ["Burnout", "Low mood", "Overthinking"],
    style: "Humor, gentle reassurance, and easy routines that feel doable.",
    availability: "Friday • Night slots open",
    formats: ["Video", "Chat"],
    fee: "Demo profile",
    accent: "from-slate-700 to-indigo-700",
    badgeTone: "bg-slate-100 text-slate-700 ring-slate-300/70",
    bio: "Shinchan brings a playful tone that can make tough days feel less heavy while still helping users find small, realistic next steps.",
    slots: [
      "Friday • 7:00 PM",
      "Friday • 9:00 PM",
      "Saturday • 10:00 AM",
    ],
  },
  {
    id: "doraemon",
    name: "Doraemon",
    civilianName: "Future-ready comfort guide",
    image: doraemonPortrait,
    imageAlt: "Stylized portrait of Doraemon as a counsellor",
    tagline: "Gentle encouragement for belonging, change, and everyday worries.",
    focus: ["Belonging", "Life changes", "College life"],
    style: "Soft encouragement, practical help, and a comforting presence.",
    availability: "Saturday • Flexible slots",
    formats: ["Video", "Voice", "Chat"],
    fee: "Demo profile",
    accent: "from-fuchsia-500 to-violet-600",
    badgeTone: "bg-fuchsia-50 text-fuchsia-700 ring-fuchsia-200/70",
    bio: "Doraemon is a reassuring fit for users working through change, self-doubt, or the feeling that everything is piling up at once.",
    slots: [
      "Saturday • 12:00 PM",
      "Saturday • 3:30 PM",
      "Sunday • 5:00 PM",
    ],
  },
];
